-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "dino"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = "#fadf7d" })
hi(0, "@attribute", { fg = "#e9e2db" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@boolean", { fg = "#c8b4df" })
hi(0, "@character", { fg = "#fadf7d" })
hi(0, "@character.special", { fg = "#fadf7d" })
hi(0, "@comment", { fg = "#726a73", italic = true })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@conditional", { fg = "#ff89ae" })
hi(0, "@constant", { fg = "#c8b4df" })
hi(0, "@constant.builtin", { fg = "#c8b4df" })
hi(0, "@constant.macro", { fg = "#96c3db" })
hi(0, "@constructor", { fg = "#e9e2db" })
hi(0, "@define", { fg = "#ff89ae" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@error", { bg = "#121217", bold = true, fg = "#e5605f" })
hi(0, "@exception", { fg = "#ff89ae" })
hi(0, "@field", { fg = "#e9e2db" })
hi(0, "@float", { fg = "#c8b4df" })
hi(0, "@function", { fg = "#89cfa8" })
hi(0, "@function.builtin", { fg = "#89cfa8" })
hi(0, "@function.call", { fg = "#89cfa8" })
hi(0, "@function.macro", { fg = "#96c3db" })
hi(0, "@include", { fg = "#ff89ae" })
hi(0, "@keyword", { fg = "#ff89ae" })
hi(0, "@keyword.function", { fg = "#ff89ae" })
hi(0, "@keyword.operator", { fg = "#ff89ae" })
hi(0, "@keyword.return", { fg = "#ff89ae" })
hi(0, "@label", { fg = "#c8b4df" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@method", { fg = "#89cfa8" })
hi(0, "@method.call", { fg = "#89cfa8" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = "#96c3db" })
hi(0, "@none", { fg = "#ec8d97" })
hi(0, "@number", { fg = "#c8b4df" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#ff89ae" })
hi(0, "@parameter", { fg = "#e9e2db" })
hi(0, "@parameter.reference", { fg = "#e9e2db" })
hi(0, "@preproc", { fg = "#ff89ae" })
hi(0, "@property", { fg = "#e9e2db" })
hi(0, "@punctuation.bracket", { fg = "#9e928e" })
hi(0, "@punctuation.delimiter", { fg = "#9e928e" })
hi(0, "@punctuation.special", { fg = "#9e928e" })
hi(0, "@repeat", { fg = "#ff89ae" })
hi(0, "@storageclass", { fg = "#96c3db" })
hi(0, "@string", { fg = "#fadf7d" })
hi(0, "@string.escape", { fg = "#c3a3e8" })
hi(0, "@string.regex", { fg = "#fadf7d" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@symbol", { fg = "#e9e2db" })
hi(0, "@tag", { fg = "#ff89ae" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#9e928e" })
hi(0, "@text", { fg = "#e9e2db" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { fg = "#fadf7d" })
hi(0, "@text.strong", { fg = "#fadf7d" })
hi(0, "@text.title", { bold = true, fg = "#e9e2db" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#fadf7d", underline = true })
hi(0, "@todo", { bold = true, fg = "#ec8d97" })
hi(0, "@type", { fg = "#96c3db" })
hi(0, "@type.builtin", { fg = "#ff89ae" })
hi(0, "@type.definition", { fg = "#ff89ae" })
hi(0, "@type.qualifier", { fg = "#ff89ae" })
hi(0, "@variable", { fg = "#e9e2db" })
hi(0, "@variable.builtin", { fg = "#c8b4df" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#bfffcc" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#c3a3e8" })
hi(0, "BufferCurrent", { bg = "#322f32", fg = "#e9e2db" })
hi(0, "BufferCurrentIndex", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferCurrentMod", { bg = "#121217", fg = "#fadf7d" })
hi(0, "BufferCurrentSign", { bg = "#121217", fg = "#96c3db" })
hi(0, "BufferCurrentTarget", { bg = "#121217", bold = true, fg = "#ff89ae" })
hi(0, "BufferInactive", { bg = "#1a191e", fg = "#897d87" })
hi(0, "BufferInactiveIndex", { bg = "#1a191e", fg = "#897d87" })
hi(0, "BufferInactiveMod", { bg = "#1a191e", fg = "#fadf7d" })
hi(0, "BufferInactiveSign", { bg = "#1a191e", fg = "#897d87" })
hi(0, "BufferInactiveTarget", { bg = "#1a191e", bold = true, fg = "#ff89ae" })
hi(0, "BufferLineBackground", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineBufferVisible", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineCloseButton", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineCloseButtonVisible", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineDuplicate", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineDuplicateVisible", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineFill", { bg = "#1a191e", bold = true, fg = "#e9e2db" })
hi(0, "BufferLineModified", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineModifiedVisible", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineSeparator", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferLineTab", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferVisible", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferVisibleIndex", { bg = "#121217", fg = "#e9e2db" })
hi(0, "BufferVisibleMod", { bg = "#121217", fg = "#fadf7d" })
hi(0, "BufferVisibleSign", { bg = "#121217", fg = "#89cfa8" })
hi(0, "BufferVisibleTarget", { bg = "#121217", bold = true, fg = "#ff89ae" })
hi(0, "Changed", { ctermfg = 14, fg = "#a9ffff" })
hi(0, "Character", { fg = "#fadf7d" })
hi(0, "CmpDocumentation", { fg = "#e9e2db" })
hi(0, "CmpDocumentationBorder", { fg = "#897d87" })
hi(0, "CmpItemAbbr", { fg = "#e9e2db" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#726a73" })
hi(0, "CmpItemAbbrMatch", { fg = "#96c3db" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#96c3db" })
hi(0, "CmpItemKind", { fg = "#89cfa8" })
hi(0, "CmpItemKindClass", { fg = "#ff89ae" })
hi(0, "CmpItemKindConstant", { fg = "#ec8d97" })
hi(0, "CmpItemKindConstructor", { fg = "#fadf7d" })
hi(0, "CmpItemKindEnum", { fg = "#96c3db" })
hi(0, "CmpItemKindEnumMember", { fg = "#ec8d97" })
hi(0, "CmpItemKindField", { fg = "#e9e2db" })
hi(0, "CmpItemKindKeyword", { fg = "#c8b4df" })
hi(0, "CmpItemKindMethod", { fg = "#96c3db" })
hi(0, "CmpItemKindOperator", { fg = "#ff89ae" })
hi(0, "CmpItemKindProperty", { fg = "#e9e2db" })
hi(0, "CmpItemKindStruct", { fg = "#96c3db" })
hi(0, "CmpItemKindVariabl", { fg = "#e9e2db" })
hi(0, "CmpItemMenu", { fg = "#c8b4df" })
hi(0, "CodeActionMenuDetailsDisabled", { fg = "#726a73" })
hi(0, "CodeActionMenuDetailsLabel", { fg = "#fadf7d" })
hi(0, "CodeActionMenuDetailsPreferred", { fg = "#89cfa8" })
hi(0, "CodeActionMenuDetailsTitle", { fg = "#e9e2db" })
hi(0, "CodeActionMenuDetailsUndefined", { fg = "#726a73" })
hi(0, "CodeActionMenuMenuDisabled", { fg = "#726a73" })
hi(0, "CodeActionMenuMenuIndex", { fg = "#96c3db" })
hi(0, "CodeActionMenuMenuKind", { fg = "#89cfa8" })
hi(0, "CodeActionMenuMenuSelection", { fg = "#96c3db" })
hi(0, "CodeActionMenuMenuTitle", { fg = "#e9e2db" })
hi(0, "CodeActionMenuWarningMessageBorder", { fg = "#ff89ae" })
hi(0, "CodeActionMenuWarningMessageText", { fg = "#efa570" })
hi(0, "ColorColumn", { bg = "#29292e" })
hi(0, "Comment", { fg = "#726a73", italic = true })
hi(0, "Conceal", { fg = "#e9e2db" })
hi(0, "Conditional", { fg = "#ff89ae" })
hi(0, "Constant", { fg = "#c8b4df" })
hi(0, "CurSearch", { bg = "#fce094", ctermbg = 11, ctermfg = 0, fg = "#121319" })
hi(0, "Cursor", { bg = "#121217", fg = "#fadf7d" })
hi(0, "CursorColumn", {})
hi(0, "CursorLine", { bg = "#29292e" })
hi(0, "CursorLineNr", { bg = "#121217", bold = true, fg = "#e9e2db" })
hi(0, "DashboardCenter", { fg = "#e9e2db" })
hi(0, "DashboardFooter", { fg = "#fadf7d" })
hi(0, "DashboardHeader", { fg = "#89cfa8" })
hi(0, "Debug", { fg = "#e9e2db" })
hi(0, "Define", { fg = "#96c3db" })
hi(0, "Delimiter", { fg = "#9e928e" })
hi(0, "DiagnosticError", { ctermfg = 9, fg = "#e5605f" })
hi(0, "DiagnosticFloatingError", { fg = "#e5605f" })
hi(0, "DiagnosticFloatingHint", { fg = "#96c3db" })
hi(0, "DiagnosticFloatingInfo", { fg = "#fadf7d" })
hi(0, "DiagnosticFloatingWarn", { fg = "#efa570" })
hi(0, "DiagnosticHint", { ctermfg = 12, fg = "#96c3db" })
hi(0, "DiagnosticInfo", { ctermfg = 14, fg = "#fadf7d" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#bfffcc" })
hi(0, "DiagnosticSignError", { bg = "#121217", fg = "#e5605f" })
hi(0, "DiagnosticSignHint", { bg = "#121217", fg = "#96c3db" })
hi(0, "DiagnosticSignInfo", { bg = "#121217", fg = "#fadf7d" })
hi(0, "DiagnosticSignWarn", { bg = "#121217", fg = "#efa570" })
hi(0, "DiagnosticVirtualTextError", { fg = "#e5605f" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#897d87" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#fadf7d" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#efa570" })
hi(0, "DiagnosticWarn", { ctermfg = 11, fg = "#efa570" })
hi(0, "DiffAdd", { bg = "#005523", ctermbg = 10, ctermfg = 0, fg = "#89cfa8" })
hi(0, "DiffAdded", { fg = "#89cfa8" })
hi(0, "DiffChange", { bg = "#4f5258", fg = "#89cfa8" })
hi(0, "DiffDelete", { bold = true, ctermfg = 9, fg = "#ff89ae" })
hi(0, "DiffFile", { fg = "#c8b4df" })
hi(0, "DiffRemoved", { fg = "#ff89ae" })
hi(0, "DiffText", { bg = "#007373", ctermbg = 14, ctermfg = 0, fg = "#e9e2db" })
hi(0, "DiffViewNormal", { bg = "#1a191e", fg = "#897d87" })
hi(0, "DiffviewFilePanelDeletion", { fg = "#e5605f" })
hi(0, "DiffviewFilePanelInsertion", { fg = "#97e38c" })
hi(0, "DiffviewStatusAdded", { fg = "#97e38c" })
hi(0, "DiffviewStatusDeleted", { fg = "#e5605f" })
hi(0, "DiffviewStatusModified", { fg = "#77b9cb" })
hi(0, "DiffviewStatusRenamed", { fg = "#77b9cb" })
hi(0, "DiffviewVertSplit", { bg = "#121217" })
hi(0, "Directory", { ctermfg = 14, fg = "#e9e2db" })
hi(0, "Error", { bg = "#121217", bold = true, ctermbg = 9, ctermfg = 0, fg = "#ff89ae" })
hi(0, "ErrorMsg", { bg = "#d95555", bold = true, ctermfg = 9, fg = "#3b383b" })
hi(0, "Exception", { fg = "#e9e2db" })
hi(0, "Float", { fg = "#ec8d97" })
hi(0, "FloatBorder", { fg = "#897d87" })
hi(0, "FlutterWidgetGuides", { fg = "#897d87" })
hi(0, "FoldColumn", { bg = "#121217", fg = "#5c545b" })
hi(0, "Folded", { bg = "#322f32", fg = "#e9e2db" })
hi(0, "Function", { ctermfg = 14, fg = "#89cfa8" })
hi(0, "GitGutterAdd", { fg = "#97e38c" })
hi(0, "GitGutterChange", { fg = "#77b9cb" })
hi(0, "GitGutterDelete", { fg = "#e5605f" })
hi(0, "GitSignsAdd", { bg = "#121217", fg = "#89cfa8" })
hi(0, "GitSignsChange", { bg = "#121217", fg = "#77b9cb" })
hi(0, "GitSignsDelete", { bg = "#121217", fg = "#ff89ae" })
hi(0, "Identifier", { ctermfg = 12, fg = "#e9e2db" })
hi(0, "Ignore", { fg = "#9e928e" })
hi(0, "IncSearch", { bg = "#e0828d", fg = "#27262d" })
hi(0, "Include", { fg = "#96c3db" })
hi(0, "IndentBlanklineChar", { fg = "#323238" })
hi(0, "IndentBlanklineContextChar", { fg = "#897d87" })
hi(0, "IndentBlanklineSpaceChar", { fg = "#e9e2db" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#fadf7d" })
hi(0, "IndentGuidesEven", { fg = "#e9e2db" })
hi(0, "IndentGuidesOdd", { fg = "#726a73" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#ff89ae" })
hi(0, "Label", { fg = "#ff89ae" })
hi(0, "LineNr", { bg = "#121217", fg = "#5c545b" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#e5605f" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#96c3db" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#fadf7d" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#fadf7d" })
hi(0, "LspDiagnosticsError", { fg = "#e5605f" })
hi(0, "LspDiagnosticsFloatingError", { fg = "#e5605f" })
hi(0, "LspDiagnosticsFloatingHint", { fg = "#96c3db" })
hi(0, "LspDiagnosticsFloatingInformation", { fg = "#fadf7d" })
hi(0, "LspDiagnosticsFloatingWarning", { fg = "#efa570" })
hi(0, "LspDiagnosticsHint", { fg = "#96c3db" })
hi(0, "LspDiagnosticsInformation", { fg = "#fadf7d" })
hi(0, "LspDiagnosticsSignError", { fg = "#e5605f" })
hi(0, "LspDiagnosticsSignHint", { fg = "#96c3db" })
hi(0, "LspDiagnosticsSignInformation", { fg = "#fadf7d" })
hi(0, "LspDiagnosticsSignWarning", { fg = "#efa570" })
hi(0, "LspDiagnosticsUnderlineError", { underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { underline = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#897d87" })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#fadf7d" })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#efa570" })
hi(0, "LspDiagnosticsWarning", { fg = "#efa570" })
hi(0, "LspReferenceRead", { bold = true })
hi(0, "LspReferenceText", { bold = true })
hi(0, "LspReferenceWrite", { bold = true })
hi(0, "Macro", { fg = "#96c3db" })
hi(0, "MatchParen", { bg = "#1a191e", bold = true, fg = "#e9e2db" })
hi(0, "MatchParenCur", { underline = true })
hi(0, "MatchWord", { underline = true })
hi(0, "MatchWordCur", { underline = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniJump2dSpot", { bg = "#121217", bold = true, fg = "#ffffff", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#121217", fg = "#8a8a8a", nocombine = true })
hi(0, "ModeMsg", { bg = "#121217", ctermfg = 10, fg = "#e9e2db" })
hi(0, "MoreMsg", { ctermfg = 14, fg = "#efa570" })
hi(0, "MsgArea", { bg = "#121217", fg = "#e9e2db" })
hi(0, "MsgSeparator", { bg = "#121217", fg = "#e9e2db" })
hi(0, "NERDTreeBookmark", { fg = "#ec8d97" })
hi(0, "NERDTreeBookmarkName", { fg = "#ec8d97" })
hi(0, "NERDTreeBookmarksHeader", { fg = "#ff89ae" })
hi(0, "NERDTreeBookmarksLeader", { fg = "#96c3db" })
hi(0, "NERDTreeCWD", { fg = "#ff89ae" })
hi(0, "NERDTreeClosable", { fg = "#ff89ae" })
hi(0, "NERDTreeCurrentNode", { fg = "#726a73" })
hi(0, "NERDTreeDir", { fg = "#96c3db" })
hi(0, "NERDTreeDirSlash", { fg = "#726a73" })
hi(0, "NERDTreeExecFile", { fg = "#89cfa8" })
hi(0, "NERDTreeFile", { fg = "#e9e2db" })
hi(0, "NERDTreeFlags", { fg = "#ff89ae" })
hi(0, "NERDTreeHelpCommand", { fg = "#fadf7d" })
hi(0, "NERDTreeHelpKey", { fg = "#e9e2db" })
hi(0, "NERDTreeHelpTitle", { fg = "#c8b4df" })
hi(0, "NERDTreeIgnore", { fg = "#726a73" })
hi(0, "NERDTreeLinkDir", { fg = "#c8b4df" })
hi(0, "NERDTreeLinkFile", { fg = "#89cfa8" })
hi(0, "NERDTreeLinkTarget", { fg = "#96c3db" })
hi(0, "NERDTreeNodeDelimiters", { fg = "#726a73" })
hi(0, "NERDTreeOpenable", { fg = "#726a73" })
hi(0, "NERDTreePart", { fg = "#ec8d97" })
hi(0, "NERDTreePartFile", { fg = "#96c3db" })
hi(0, "NERDTreeRO", { fg = "#ec8d97" })
hi(0, "NERDTreeToggleOff", { fg = "#ec8d97" })
hi(0, "NERDTreeToggleOn", { fg = "#89cfa8" })
hi(0, "NERDTreeUp", { fg = "#fadf7d" })
hi(0, "NeogitBranch", { fg = "#c8b4df" })
hi(0, "NeogitDiffAdd", { bg = "#1a191e", fg = "#97e38c" })
hi(0, "NeogitDiffAddHighlight", { bg = "#1a191e", fg = "#97e38c" })
hi(0, "NeogitDiffContext", { bg = "#121217", fg = "#c6c6c6" })
hi(0, "NeogitDiffContextHighlight", { bg = "#121217", fg = "#c6c6c6" })
hi(0, "NeogitDiffDelete", { bg = "#1a191e", fg = "#e5605f" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#1a191e", fg = "#e5605f" })
hi(0, "NeogitHunkHeader", { bg = "#1a191e", fg = "#c6c6c6" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#1a191e", fg = "#c6c6c6" })
hi(0, "NeogitRemote", { fg = "#c8b4df" })
hi(0, "NonText", { fg = "#897d87" })
hi(0, "Normal", { bg = "#121217", fg = "#e9e2db" })
hi(0, "NormalFloat", { bg = "#121217" })
hi(0, "NormalNC", { bg = "#121217", fg = "#e9e2db" })
hi(0, "Number", { fg = "#ec8d97" })
hi(0, "NvimInternalError", { bg = "#ff0000", ctermbg = 9, ctermfg = 9, fg = "#ff3e2f" })
hi(0, "NvimTreeCursorLine", { bg = "#29292e", fg = "#5c545b" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#fadf7d", italic = true })
hi(0, "NvimTreeEndOfBuffer", { fg = "#897d87" })
hi(0, "NvimTreeExecFile", { fg = "#89cfa8" })
hi(0, "NvimTreeFolderIcon", { fg = "#726a73" })
hi(0, "NvimTreeFolderName", { fg = "#e9e2db" })
hi(0, "NvimTreeGitDeleted", { fg = "#e5605f" })
hi(0, "NvimTreeGitDirty", { fg = "#97e38c" })
hi(0, "NvimTreeGitMerge", { fg = "#77b9cb" })
hi(0, "NvimTreeGitNew", { fg = "#97e38c" })
hi(0, "NvimTreeGitRenamed", { fg = "#77b9cb" })
hi(0, "NvimTreeGitStaged", { fg = "#97e38c" })
hi(0, "NvimTreeImageFile", { fg = "#c8b4df" })
hi(0, "NvimTreeIndentMarker", { fg = "#726a73" })
hi(0, "NvimTreeNormal", { bg = "#1a191e", fg = "#e9e2db" })
hi(0, "NvimTreeNormalNC", { bg = "#1a191e" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#e9e2db", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#fadf7d" })
hi(0, "NvimTreeSpecialFile", { fg = "#ec8d97" })
hi(0, "NvimTreeSymlink", { fg = "#fadf7d" })
hi(0, "NvimTreeVertSplit", { fg = "#242328" })
hi(0, "Operator", { fg = "#e9e2db" })
hi(0, "Pmenu", { bg = "#1a191e", fg = "#e9e2db" })
hi(0, "PmenuSbar", { bg = "#322f32" })
hi(0, "PmenuSel", { bg = "#1a191e", blend = 0, fg = "#5c545b" })
hi(0, "PmenuThumb", { bg = "#1a191e" })
hi(0, "PreCondit", { fg = "#96c3db" })
hi(0, "PreProc", { fg = "#96c3db" })
hi(0, "Question", { ctermfg = 14, fg = "#89cfa8" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#efa570" })
hi(0, "Removed", { ctermfg = 9, fg = "#ffccc5" })
hi(0, "Repeat", { fg = "#ff89ae" })
hi(0, "Search", { bg = "#e0828d", ctermbg = 11, ctermfg = 0, fg = "#5c545b" })
hi(0, "SignColumn", { bg = "#121217" , fg = "#595c62" })
hi(0, "Special", { ctermfg = 14, fg = "#9e928e" })
hi(0, "SpecialChar", { fg = "#fadf7d" })
hi(0, "SpecialComment", { fg = "#c8b4df" })
hi(0, "SpecialKey", { bold = true, fg = "#9e928e" })
hi(0, "SpellBad", { fg = "#ff89ae", sp = "#ffc0b9", underline = true })
hi(0, "SpellCap", { fg = "#ec8d97", sp = "#fce094", underline = true })
hi(0, "SpellLocal", { fg = "#89cfa8", sp = "#b3f6c0", underline = true })
hi(0, "SpellRare", { fg = "#c8b4df", sp = "#8cf8f7", underline = true })
hi(0, "StartifyBracket", { fg = "#e9e2db" })
hi(0, "StartifyEndOfBuffer", { fg = "#897d87" })
hi(0, "StartifyFile", { fg = "#96c3db" })
hi(0, "StartifyFooter", { fg = "#c8b4df" })
hi(0, "StartifyHeader", { fg = "#96c3db" })
hi(0, "StartifyNumber", { fg = "#ff89ae" })
hi(0, "StartifyPath", { fg = "#726a73" })
hi(0, "StartifySection", { fg = "#c8b4df" })
hi(0, "StartifySelect", { fg = "#726a73" })
hi(0, "StartifySlash", { fg = "#726a73" })
hi(0, "StartifySpecial", { fg = "#fadf7d" })
hi(0, "StartifyVar", { fg = "#726a73" })
hi(0, "Statement", { bold = true, fg = "#ff89ae" })
hi(0, "StatusLine", { bg = "#121217", fg = "#ffffff" })
hi(0, "StatusLineNC", { bg = "#121217", fg = "#242328" })
hi(0, "StatusLineSeparator", { fg = "#242328" })
hi(0, "StatusLineTerm", { bg = "#1a191e", fg = "#89cfa8" })
hi(0, "StatusLineTermNC", { bg = "#1a191e", fg = "#9e928e" })
hi(0, "StorageClass", { fg = "#96c3db" })
hi(0, "String", { ctermfg = 10, fg = "#fadf7d" })
hi(0, "Structure", { fg = "#89cfa8" })
hi(0, "Substitute", { bg = "#e0828d", fg = "#897d87" })
hi(0, "TabLine", { fg = "#5c545b" })
hi(0, "TabLineFill", { fg = "#5c545b" })
hi(0, "TabLineSel", { bold = true, fg = "#e9e2db" })
hi(0, "Tag", { fg = "#9e928e" })
hi(0, "TelescopeBorder", { bg = "#121217", fg = "#e9e2db" })
hi(0, "TelescopeMatching", { fg = "#96c3db" })
hi(0, "TelescopePromptPrefix", { fg = "#89cfa8" })
hi(0, "TelescopeSelection", { bg = "#1a191e", fg = "#5c545b" })
hi(0, "TermCursor", { bg = "#aeafad", fg = "#e9e2db", reverse = true })
hi(0, "TermCursorNC", { bg = "#aeafad", fg = "#e9e2db" })
hi(0, "Title", { bold = true, fg = "#9e928e" })
hi(0, "Todo", { bold = true, fg = "#fadf7d" })
hi(0, "TroubleCode", { fg = "#efa570" })
hi(0, "TroubleCount", { fg = "#ff89ae" })
hi(0, "TroubleError", { bg = "#524a51", fg = "#ff89ae" })
hi(0, "TroubleFile", { fg = "#fadf7d" })
hi(0, "TroubleFoldIcon", { fg = "#96c3db" })
hi(0, "TroubleHint", { fg = "#efa570" })
hi(0, "TroubleIndent", { fg = "#726a73" })
hi(0, "TroubleInformation", { fg = "#e9e2db" })
hi(0, "TroubleLocation", { fg = "#e9e2db" })
hi(0, "TroubleNormal", { fg = "#e9e2db" })
hi(0, "TroublePreview", { fg = "#ff89ae" })
hi(0, "TroubleSignError", { fg = "#ff89ae" })
hi(0, "TroubleSignHint", { fg = "#89cfa8" })
hi(0, "TroubleSignInformation", { fg = "#e9e2db" })
hi(0, "TroubleSignOther", { fg = "#89cfa8" })
hi(0, "TroubleSignWarning", { fg = "#efa570" })
hi(0, "TroubleSource", { fg = "#96c3db" })
hi(0, "TroubleText", { fg = "#e9e2db" })
hi(0, "TroubleTextError", { fg = "#ff89ae" })
hi(0, "TroubleTextHint", { fg = "#e9e2db" })
hi(0, "TroubleTextInformation", { fg = "#96c3db" })
hi(0, "TroubleTextWarning", { fg = "#efa570" })
hi(0, "TroubleWarning", { fg = "#efa570" })
hi(0, "Type", { fg = "#96c3db" })
hi(0, "Typedef", { fg = "#96c3db" })
hi(0, "Variable", { fg = "#e9e2db" })
hi(0, "VertSplit", { fg = "#37323a" })
hi(0, "Visual", { bg = "#29292e", bold = true, ctermbg = 15, ctermfg = 0 })
hi(0, "VisualNOS", { bg = "#817081", fg = "#6b5c6c" })
hi(0, "WarningMsg", { bg = "#121217", ctermfg = 11, fg = "#efa570" }) 
hi(0, "WhichKey", { fg = "#96c3db" })
hi(0, "WhichKeyDesc", { fg = "#e9e2db" })
hi(0, "WhichKeyFloat", { bg = "#1a191e" })
hi(0, "WhichKeyGroup", { fg = "#c8b4df" })
hi(0, "WhichKeySeperator", { fg = "#ff89ae" })
hi(0, "Whitespace", { fg = "#897d87" })
hi(0, "WildMenu", { fg = "#e9e2db" })
hi(0, "WinBar", { bg = "#07080d", bold = true, fg = "#a6a9af" })
hi(0, "WinBarNC", { bg = "#07080d", fg = "#a6a9af" })
hi(0, "cmakeArguments", { fg = "#e9e2db" })
hi(0, "cmakeCommand", { fg = "#e9e2db" })
hi(0, "cmakeGeneratorExpressions", { fg = "#c8b4df" })
hi(0, "cmakeKWproject", { fg = "#c8b4df" })
hi(0, "cmakeKWuse_mangled_mesa", { fg = "#e9e2db", italic = true })
hi(0, "cmakeKWvariable_watch", { fg = "#e9e2db" })
hi(0, "cmakeVariable", { fg = "#e9e2db" })
hi(0, "debugBreakpoint", { fg = "#ff89ae", reverse = true })
hi(0, "debugPc", { bg = "#ded7d0" })
hi(0, "lCursor", { bg = "#aeafad", fg = "#e9e2db" })
hi(0, "markdownBlockquote", { fg = "#c6c6c6" })
hi(0, "markdownBold", { bold = true, fg = "#e9e2db" })
hi(0, "markdownCode", { fg = "#ec8d97" })
hi(0, "markdownCodeBlock", { fg = "#ec8d97" })
hi(0, "markdownCodeDelimiter", { fg = "#89cfa8" })
hi(0, "markdownCodeError", { fg = "#e5605f" })
hi(0, "markdownCodeSpecial", { fg = "#ec8d97" })
hi(0, "markdownH1", { fg = "#e9e2db" })
hi(0, "markdownH2", { fg = "#e9e2db" })
hi(0, "markdownH3", { fg = "#e9e2db" })
hi(0, "markdownH4", { fg = "#e9e2db" })
hi(0, "markdownH5", { fg = "#e9e2db" })
hi(0, "markdownH6", { fg = "#e9e2db" })
hi(0, "markdownHeadingDelimiter", { fg = "#e9e2db" })
hi(0, "markdownHeadingRule", { fg = "#c6c6c6" })
hi(0, "markdownId", { fg = "#c8b4df" })
hi(0, "markdownIdDeclaration", { fg = "#e9e2db" })
hi(0, "markdownIdDelimiter", { fg = "#897d87" })
hi(0, "markdownItalic", { italic = true })
hi(0, "markdownLinkDelimiter", { fg = "#897d87" })
hi(0, "markdownLinkText", { fg = "#e9e2db" })
hi(0, "markdownListMarker", { fg = "#ff89ae" })
hi(0, "markdownOrderedListMarker", { fg = "#ff89ae" })
hi(0, "markdownRule", { fg = "#c6c6c6" })
hi(0, "markdownUrl", { fg = "#c8b4df", underline = true })
hi(0, "markdownUrlTitleDelimiter", { fg = "#e9e2db" })
hi(0, "pythonBoolean", { fg = "#e9e2db" })
hi(0, "pythonConditional", { fg = "#ff89ae" })
hi(0, "pythonException", { fg = "#c8b4df" })
hi(0, "pythonFunction", { fg = "#89cfa8" })
hi(0, "pythonInclude", { fg = "#ff89ae" })
hi(0, "pythonOperator", { fg = "#ff89ae" })
hi(0, "pythonStatement", { fg = "#e9e2db" })


-- No terminal colors defined
